### ISSUE TITLE
Differentiate between Sass and SCSS

### ISSUE THREAD

**Issue by jonathantneal** [10up/grunt-wp-theme#14]
Might this plugin offer either **Sass** or **SCSS** as a configuration option, or otherwise amend the existing **Sass** reference to instead read **SCSS**?

I ask because [line 40 of template.js](https://github.com/10up/grunt-wp-theme/blob/master/template.js#L40) asks the user whether they would like to use **Sass**, **LESS**, or **CSS** with their project. Pardon me if I’m outdated on the colloquial understanding of **Sass**, but I believe that term refers to the original, lighter, but less preferred syntax, whereas this tool actually produces **SCSS**, the more common and preferred [Sassy CSS](https://github.com/10up/grunt-wp-theme/blob/master/root/assets/css/sass/theme.scss) syntax.

[What’s the Difference Between Sass and SCSS?](http://www.sitepoint.com/whats-difference-sass-scss/)

**Comment by ericmann** [comment]
The preprocessor is called Sass, whether you use .sass or .scss files/syntax with it. The filetype/syntax you decide to use in your project is beside the point, the system only needs to know that you're using Sass (the processor) to set up the Grunt includes.
