### ISSUE TITLE
Allow other licenses

### ISSUE THREAD

**Issue by jonathantneal** [10up/grunt-wp-theme#15]
Might this plugin support the scaffolding of [GPL-compatible licenses](http://www.gnu.org/philosophy/license-list.html#GPLCompatibleLicenses/) like CC0 (Public Domain)?

> Themes are required to be 100% GPL-licensed, or use a [GPL-compatible license](http://www.gnu.org/philosophy/license-list.html#GPLCompatibleLicenses/).
> [Theme Review Team, Licensing](https://make.wordpress.org/themes/handbook/guidelines/license-theme-name-credit-links-up-sell-themes/)

---
> The "MIT" license is compatible with the GPL and can be used in WordPress plugins.
> [Mark Jaquith](https://twitter.com/markjaquith/status/188108457386311681)

**Comment by ericmann** [comment]
Agreed with @tddewey here. This is a quick scaffold. If your theme aims to use a different yet GPL-compatible license, feel free. This is a starting point, nothing more.
